SUPER_CONFIG_PATH: ./configs/dancetrack.yaml

DATASETS: [SportsMOT]
DATASET_SPLITS: [train]
INFERENCE_DATASET: SportsMOT
INFERENCE_SPLIT: val

SAMPLE_LENGTHS: [60, ]

DETR_PRETRAIN: ./pretrains/r50_deformable_detr_coco_sportsmot.pth

REL_PE_LENGTH: 60

EPOCHS: 13
SCHEDULER_MILESTONES: [8, 12, ]

MISS_TOLERANCE: 60          # tolerance for missing frames

USE_DECODER_CHECKPOINT: True


# For TCEI
POS_ENABLED: True
POS_SHOT_CAPACITY: 3
POS_ALPHA: 1.0
POS_BETA: 3.0

NEG_ENABLED: True
NEG_SHOT_CAPACITY: 2
NEG_ALPHA: 0.117
NEG_BETA: 1.5
NEG_ENTROPY_THRESHOLD_LOWER: 0.2
NEG_ENTROPY_THRESHOLD_UPPER: 0.5
NEG_MASK_THRESHOLD_LOWER: 0.03
NEG_MASK_THRESHOLD_UPPER: 1.0

POS_TEMPERATURE: 0.05
NEG_TEMPERATURE: 0.05

W_POS_ENABLED: True
W_POS_SHOT_CAPACITY: 3
W_POS_ALPHA: 1.0
W_POS_BETA: 5.0

W_NEG_ENABLED: True
W_NEG_SHOT_CAPACITY: 2
W_NEG_ALPHA: 0.117
W_NEG_BETA: 2.0
W_NEG_ENTROPY_THRESHOLD_LOWER: 0.2
W_NEG_ENTROPY_THRESHOLD_UPPER: 0.5
W_NEG_MASK_THRESHOLD_LOWER: 0.03
W_NEG_MASK_THRESHOLD_UPPER: 1.0

W_POS_TEMPERATURE: 0.5
W_NEG_TEMPERATURE: 0.5

# Lambda
USE_CACHE: object_and_id
LAMBDA_OBJECT: 1.0
LAMBDA_ID: 1.0

